export const BANKS = [
  'BBVA',
  'Banorte',
  'Santander',
  'Citibanamex',
  'HSBC',
  'Scotiabank',
  'Banco Azteca',
  'BanCoppel',
  'Inbursa',
  'American Express',
  'Liverpool',
  'Palacio de Hierro',
  'Nu',
  'Hey Banco',
  'Rappi',
  'Stori',
  'Klar',
  'Mercado Pago',
  'Revolut',
  'GBM',
  'CETES Directo',
  'Otro',
] as const

export const VOUCHER_BRANDS = [
  'Pluxee (Sodexo)',
  'Efectivale',
  'SíVale',
  'Edenred',
  'Up Sí Vale',
  'Otro',
] as const
