ALTER TABLE cards ADD COLUMN IF NOT EXISTS has_yields BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE cards ADD COLUMN IF NOT EXISTS yield_rate NUMERIC(6,3);
ALTER TABLE cards ADD COLUMN IF NOT EXISTS last_yield_date DATE;
